spring:
  profiles:
    include:
    - datasource

---
spring.profiles: local
spring:
  thymeleaf:
    cache: false
---
spring.profiles: test

---
spring.profiles: dev

---
spring.profiles: beta

---
spring.profiles: prod