spring:
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:tacademy;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=mysql
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:tacademy;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=mysql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

---
spring:
  profiles: dev

---
spring:
  profiles: beta

---
spring:
  profiles: prod